### ISSUE TITLE
manage command no longer works

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.releaser#25]
In coredev 5.2 I get this with Python 2:

```
bin/manage jenkins
Traceback (most recent call last):
  File "bin/manage", line 59, in <module>
    import plone.releaser.manage
  File "/Users/maurits/shared-eggs/cp27m/plone.releaser-1.7.2-py2.7.egg/plone/releaser/manage.py", line 20, in <module>
    import keyring
  File "/Users/maurits/shared-eggs/cp27m/keyring-19.0.2-py2.7.egg/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/Users/maurits/shared-eggs/cp27m/keyring-19.0.2-py2.7.egg/keyring/core.py", line 10, in <module>
    from . import backend
  File "/Users/maurits/shared-eggs/cp27m/keyring-19.0.2-py2.7.egg/keyring/backend.py", line 38
    class KeyringBackend(metaclass=KeyringBackendMeta):
                                  ^
SyntaxError: invalid syntax
```

So the keyring dependency is too new on Python 2. In coredev 5.1 we use 4.1.1, which seems to work.

And in Python 3 I get this:

```
bin/manage jenkins
Traceback (most recent call last):
  File "bin/manage", line 62, in <module>
    sys.exit(plone.releaser.manage.manage())
  File "/Users/maurits/shared-eggs/cp37m/plone.releaser-1.7.2-py3.7.egg/plone/releaser/manage.py", line 156, in __call__
    parser.dispatch()
  File "/Users/maurits/shared-eggs/cp37m/argh-0.26.2-py3.7.egg/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/Users/maurits/shared-eggs/cp37m/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/maurits/shared-eggs/cp37m/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/maurits/shared-eggs/cp37m/argh-0.26.2-py3.7.egg/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/Users/maurits/shared-eggs/cp37m/plone.releaser-1.7.2-py3.7.egg/plone/releaser/manage.py", line 43, in jenkins_report
    for package_name, source in iter(sources.iteritems()):
AttributeError: 'SourcesFile' object has no attribute 'iteritems'
```

So plone.releaser itself has some Python 3 issues.

So various fixes are needed.

**Comment by mauritsvanrees** [comment]
I have merged my PR that pins keyring back to 4.1.1 on Python 2.7. So `bin/manage` again works on Python 2.
Next up is Python 3, see PR #26 (WIP).
