### ISSUE TITLE
Changes to versions-extra.cfg are not committed

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.releaser#57]
I just tried to release plone.releaser 2.1.0.  This failed at updating coredev:

```
Ok to update coredev versions.cfg/checkouts.cfg? (Y/n)? 
Updating buildout versions
Updating versions-extra.cfg
/Users/maurits/community/plone-coredev/6.0/versions-extra.cfg: have set 'plone.releaser = 2.1.0'.
Removing package from checkouts
/Users/maurits/community/plone-coredev/6.0/checkouts.cfg: '    plone.releaser' removed.
Committing changes.
Checking PLONE_RELEASER_MULTI_PACKAGES env variable.
PLONE_RELEASER_MULTI_PACKAGES env variable set, so not pushing to coredev.
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/../../bin/fullrelease", line 63, in <module>
    sys.exit(zest.releaser.fullrelease.main())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp311/zest.releaser-9.0.0-py3.11.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/Users/maurits/shared-eggs/cp311/zest.releaser-9.0.0-py3.11.egg/zest/releaser/baserelease.py", line 430, in run
    self._run_hooks("after")
  File "/Users/maurits/shared-eggs/cp311/zest.releaser-9.0.0-py3.11.egg/zest/releaser/baserelease.py", line 423, in _run_hooks
    utils.run_hooks(self.zest_releaser_config, which_releaser, when, self.data)
  File "/Users/maurits/shared-eggs/cp311/zest.releaser-9.0.0-py3.11.egg/zest/releaser/utils.py", line 594, in run_hooks
    run_entry_points(which_releaser, when, data)
  File "/Users/maurits/shared-eggs/cp311/zest.releaser-9.0.0-py3.11.egg/zest/releaser/utils.py", line 610, in run_entry_points
    plugin(data)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.releaser/plone/releaser/release.py", line 267, in update_other_core_branches
    g.checkout(branch_name)
  File "/Users/maurits/shared-eggs/cp311/GitPython-3.1.32-py3.11.egg/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp311/GitPython-3.1.32-py3.11.egg/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurits/shared-eggs/cp311/GitPython-3.1.32-py3.11.egg/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 5.2
  stderr: 'error: Your local changes to the following files would be overwritten by checkout:
	versions-extra.cfg
Please commit your changes or stash them before you switch branches.
Aborting'
```

This made two changes on the coredev 6.0 branch:

* Remove `plone.releaser` from `checkouts.cfg`.
* Update its version in `versions-extra.cfg`.

Problem is that the last change was not committed.

That `versions-extra.cfg` is touched at all is caused by commit 0c4b5fb2f3839942109cc8e4a6111a1545e77e37, which is a fix for issue #52.

**Comment by mauritsvanrees** [comment]
Fixed directly in commit dab84049a7995c6a45d1bc5cab6b95afc27d476f, and tested by making three releases, one of which is `plone.releaser` itself. :-)
