### ISSUE TITLE
fullrelease on `buildout.coredev#6.1` gives traceback 

### ISSUE THREAD

**Issue by petschki** [plone/plone.releaser#67]
After successfully uploading the released package you get the question:

```
Ok to update coredev versions.cfg/checkouts.cfg? (Y/n)?
```

when you hit `n` there's a traceback:

```
Traceback (most recent call last):
  File "/Users/peterm/workspace/buildout.coredev-6.1/src/plone.staticresources/../../bin/fullrelease", line 55, in <module>
    sys.exit(zest.releaser.fullrelease.main())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/baserelease.py", line 430, in run
    self._run_hooks("after")
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/baserelease.py", line 423, in _run_hooks
    utils.run_hooks(self.zest_releaser_config, which_releaser, when, self.data)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/utils.py", line 594, in run_hooks
    run_entry_points(which_releaser, when, data)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/utils.py", line 610, in run_entry_points
    plugin(data)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/plone.releaser-2.2.2-py3.11.egg/plone/releaser/release.py", line 274, in update_other_core_branches
    g.checkout(branch_name)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/GitPython-3.1.43-py3.11.egg/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/GitPython-3.1.43-py3.11.egg/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/GitPython-3.1.43-py3.11.egg/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 5.2
  stderr: 'error: pathspec '5.2' did not match any file(s) known to git'
```

if you press `Y` then the same traceback  occurs a bit later:

```
Ok to update coredev versions.cfg/checkouts.cfg? (Y/n)? y
Updating buildout versions
Updating versions.cfg
/Users/peterm/workspace/buildout.coredev-6.1/versions.cfg: have set 'plonetheme.barceloneta = 3.2.0a4'.
Updating constraints.txt
/Users/peterm/workspace/buildout.coredev-6.1/constraints.txt: have set 'plonetheme.barceloneta==3.2.0a4'.
Removing package from checkouts
/Users/peterm/workspace/buildout.coredev-6.1/checkouts.cfg: '    plonetheme.barceloneta' removed.
Committing changes.
Checking PLONE_RELEASER_MULTI_PACKAGES env variable.
ERROR: could not parse PLONE_RELEASER_MULTI_PACKAGES env var. Ignoring it.
Ok to push coredev? (Y/n)? y
Pushing changes to server.
Traceback (most recent call last):
  File "/Users/peterm/workspace/buildout.coredev-6.1/src/plonetheme.barceloneta/../../bin/fullrelease", line 55, in <module>
    sys.exit(zest.releaser.fullrelease.main())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/baserelease.py", line 430, in run
    self._run_hooks("after")
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/baserelease.py", line 423, in _run_hooks
    utils.run_hooks(self.zest_releaser_config, which_releaser, when, self.data)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/utils.py", line 594, in run_hooks
    run_entry_points(which_releaser, when, data)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/zest.releaser-9.1.3-py3.11-macosx-14.2-arm64.egg/zest/releaser/utils.py", line 610, in run_entry_points
    plugin(data)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/plone.releaser-2.2.2-py3.11.egg/plone/releaser/release.py", line 274, in update_other_core_branches
    g.checkout(branch_name)
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/GitPython-3.1.43-py3.11.egg/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/GitPython-3.1.43-py3.11.egg/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peterm/workspace/buildout.coredev-6.1/eggs/GitPython-3.1.43-py3.11.egg/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 5.2
  stderr: 'error: pathspec '5.2' did not match any file(s) known to git'
```

**Comment by mauritsvanrees** [comment]
When you are on the 6.1 branch of `buildout.coredev` and run `bin/fullrelease`, then `plone.releaser` updates the versions and checkouts on this branch.  That should work fine.

But then it switches to the 5.2 and 6.0 branches to check if the branch of the package that you are releasing, is also used in `sources.cfg` of that coredev branch.  Then it updates versions and checkouts there as well.
Very handy for me when I do lots of package releases, but it should not break when you do not have these branches checked out.  We should catch the error, warn, and continue.

**Comment by mauritsvanrees** [comment]
BTW, I have coredev checked out in three directories, simply called 5.2, 6.0, and 6.1. (And py3 which uses branch 5.2 on Python 3.). Then I run an `update-plone-coredev.sh` script to keep the 5.2, 6.0 and 6.1 branches updated in all those directories.  Otherwise in your 6.0 directory you may have a 5.2 branch that has not been updated in a year, so its `sources.cfg` and `checkouts.cfg` will be very outdated.

Here is the script:

```
#!/bin/sh
BASEDIR=~/community/plone-coredev
# for checkout in 4.3 5.0 5.1 5.2 py3 6.0; do
for checkout in 5.2 py3 6.0 6.1; do
    echo
    echo "====================="
    cd $BASEDIR/$checkout
    pwd
    git fetch
    # for branch in 4.3 5.0 5.1 5.2 6.0; do
    for branch in 5.2 6.0 6.1; do
        git checkout $branch
        git merge --ff-only
    done
    # Go back to original branch
    if test $checkout == "py3"; then
        checkout="5.2"
    fi
    git checkout $checkout
done

fresh=0
if test "x$1" == "x--full"; then
    echo "Will run full buildout."
elif test "x$1" == "x--fresh"; then
    echo "Will run fresh buildout."
    fresh=1
else
    echo "Done. Not running buildout. Call with --full or --fresh if you want."
    exit 0
fi
# Run the extra command for the active ones.
# for checkout in 5.2 py3 6.0; do
for checkout in 5.2 6.0 6.1; do
    echo
    echo "====================="
    cd $BASEDIR/$checkout
    pwd
    if test $fresh == 1; then
        if test "$checkout" == "py3"; then
            venv3.sh 3.8
        elif test "$checkout" == "6.0"; then
            venv3.sh 3.11
        elif test "$checkout" == "6.1"; then
            venv3.sh 3.11
        else
            venv27buildout.sh
        fi
    fi
    if test -e local.cfg; then
        echo "Using local.cfg instead of buildout.cfg"
        bin/buildout -c local.cfg
    else
        bin/buildout
    fi
done
```
